name: fashion_recommender
dependencies:
  - python=3.11
  - pip
  - opencv  # âœ… correct conda package name
  - pip:
      - streamlit==1.51.0
      - mediapipe==0.10.15
      - lightgbm==4.5.0
      - numpy==1.26.4
      - pandas==2.2.2
      - joblib==1.4.2
      - scikit-learn==1.5.2
