name: fashion_recommender
dependencies:
  - python=3.11
  - pip
  - pip:
      - numpy==1.26.4
      - pandas==2.2.2
      - joblib==1.4.2
      - scikit-learn==1.5.2
      - lightgbm==4.5.0
      - mediapipe==0.10.15
      - opencv-contrib-python-headless==4.10.0.84
      - streamlit==1.51.0
